version: "3"
services:
  tennishipapp:
    image: padawansurjc/tennishipapp:latest
    restart: always
    ports:
      - "8443:8443"
    networks:
      - tenniship-network
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - tennishipsql
 
  tennishipsql:
    image: mysql:8
    restart: on-failure
    ports:
      - "5000:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - tenniship-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tenniship  

networks:
  tenniship-network: 